name: Update files with commit

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.MY_GITHUB_PAT }} # You need to create your own token with commit rights
          ref: main # The branch you want to commit to


      - name: Update files
        uses: MathieuSoysal/file-updater-for-release@v1.0.3
        with:
          files: README.md # List of files to update
          prefix: "🚀 **v" # Prefix before the version
          with-checkout: false # If you don't want to checkout the repo, default is: true
      
      - name: Push changes
        uses: EndBug/add-and-commit@v9
        with:
          committer_name: GitHub Actions
          committer_email: actions@github.com
          add: .
          message: 'update files'
